### ISSUE TITLE
socketCAN Driver compilation failure in Ubuntu release- 5.15.0-41-generic , version - 20.04.1-Ubuntu

### ISSUE THREAD

**Issue by ManojAshok** [IanMurphy-Rockfort/emuc-b202#1]
Hi,

I am trying to compile emuc-b202 socketCAN driver for  20.04.1-Ubuntu , release- 5.15.0-41-generic and getting the following errors.

Requesting you fix the issue at the earliest.

Linux/EMUC_B202_SocketCAN_driver_v3.5_utility_v3.2_20220208/driver/main.c:141:19: error: initialization of ‘void (*)(struct tty_struct *, const unsigned char *, const char *, int)’ from incompatible pointer type ‘void (*)(struct tty_struct *, const unsigned char *, char *, int)’ [-Werror=incompatible-pointer-types]
  141 |   .receive_buf  = emuc_receive_buf,
      |                   ^~~~~~~~~~~~~~~~

Linux/EMUC_B202_SocketCAN_driver_v3.5_utility_v3.2_20220208/driver/main.c:226:12: error: too many arguments to function ‘tty_register_ldisc’
  226 |   status = tty_register_ldisc(N_EMUC, &emuc_ldisc);
      |            ^~~~~~~~~~~~~~~~~~
	  

Linux/EMUC_B202_SocketCAN_driver_v3.5_utility_v3.2_20220208/driver/main.c:325:5: error: void value not ignored as it ought to be
  325 |   i = tty_unregister_ldisc(N_EMUC);

Regards,
Manoj

**Comment by IanMurphy-Rockfort** [comment]
Hi Manoj,

This is not my software, it's just a mirror to host the Innodisk software in case it becomes unavailable direct from them.

Thanks, Ian

**Comment by ManojAshok** [comment]
Thanks LanMurphy,

I will contact them.
